# Generated by Django 4.0.4 on 2022-04-30 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemuseum', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='评论文本')),
                ('images', models.CharField(blank=True, max_length=255, null=True, verbose_name='评论图片')),
            ],
            options={
                'verbose_name': '用户评论',
                'db_table': 'a_comment',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='动态文本')),
                ('files_urls', models.CharField(blank=True, max_length=255, null=True, verbose_name='动态文件url')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='culturalrelicsdata',
            options={'managed': False, 'verbose_name': '文物', 'verbose_name_plural': '文物'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('cltrrlcs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cltrrlcs_stars', to='onlinemuseum.culturalrelicsdata', verbose_name='文物')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_stars', to='onlinemuseum.comment', verbose_name='评论')),
                ('dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_stars', to='onlinemuseum.dynamic', verbose_name='用户动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_star', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞记录',
                'db_table': 'a_star',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'follow'), ('c', 'comment'), ('l', 'like'), ('r', 'reply')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='动作时间')),
                ('read', models.BooleanField(verbose_name='是否已读')),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL, verbose_name='通知动作用户')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_ntfctns', to='onlinemuseum.comment', verbose_name='相关评论')),
                ('star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_ntfctns', to='onlinemuseum.star', verbose_name='相关点赞')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'db_table': 'a_notification',
            },
        ),
        migrations.AddField(
            model_name='dynamic',
            name='cltrlrlcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cltrrlcs_dynamics', to='onlinemuseum.culturalrelicsdata', verbose_name='文物'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dynamics', to=settings.AUTH_USER_MODEL, verbose_name='发布用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cltrrlcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cltrrlcs_comments', to='onlinemuseum.culturalrelicsdata', verbose_name='文物'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comments', to='onlinemuseum.comment', verbose_name='用户评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_comments', to='onlinemuseum.dynamic', verbose_name='用户动态'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_replys', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_me_follow', to=settings.AUTH_USER_MODEL, verbose_name='关注用户')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_me', to=settings.AUTH_USER_MODEL, verbose_name='被关注用户')),
            ],
            options={
                'verbose_name': '用户关注记录',
                'db_table': 'a_attention',
            },
        ),
    ]
