# Generated by Django 4.0.4 on 2022-04-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemuseum', '0003_comment_dynamic_alter_culturalrelicsdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name': '用户动态'},
        ),
        migrations.AlterModelTable(
            name='dynamic',
            table='a_dynamic',
        ),
    ]
