# Generated by Django 4.0.4 on 2022-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemuseum', '0004_alter_dynamic_options_alter_dynamic_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUrlTable',
            fields=[
                ('img_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'img_url_table',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='attention',
            options={'verbose_name': '用户关注记录', 'verbose_name_plural': '用户关注记录'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name': '用户动态', 'verbose_name_plural': '用户动态'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '用户通知', 'verbose_name_plural': '用户通知'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
    ]
